
const KEY='netsphere_networking_v2';
const seed={
devices:[
{id:1,name:'Core-Router-01',type:'Router',ip:'10.0.0.1',mac:'00:11:22:33:44:01',status:'Online',site:'HQ',vendor:'Cisco',model:'ISR 4331',os:'IOS XE',uptime:'48d 13h'},
{id:2,name:'Core-Switch-01',type:'Switch',ip:'10.0.0.2',mac:'00:11:22:33:44:02',status:'Online',site:'HQ',vendor:'Cisco',model:'Catalyst 9300',os:'IOS XE',uptime:'31d 5h'},
{id:3,name:'Edge-FW-01',type:'Firewall',ip:'10.0.0.254',mac:'00:11:22:33:44:03',status:'Warning',site:'HQ',vendor:'Fortinet',model:'FortiGate',os:'FortiOS',uptime:'12d 9h'},
{id:4,name:'Branch-Router-01',type:'Router',ip:'10.10.0.1',mac:'00:11:22:33:55:01',status:'Offline',site:'Branch A',vendor:'MikroTik',model:'CCR',os:'RouterOS',uptime:'0d'}
],
interfaces:[
{id:11,device:'Core-Router-01',name:'GigabitEthernet0/0',ip:'10.0.0.1/24',speed:'1 Gbps',status:'Up',vlan:'10',rx:'4.2 GB',tx:'3.1 GB'},
{id:12,device:'Core-Switch-01',name:'Gi1/0/1',ip:'10.0.0.2/24',speed:'1 Gbps',status:'Up',vlan:'10',rx:'8.7 GB',tx:'7.2 GB'},
{id:13,device:'Edge-FW-01',name:'WAN1',ip:'203.0.113.10/30',speed:'1 Gbps',status:'Up',vlan:'WAN',rx:'24.8 GB',tx:'18.1 GB'},
{id:14,device:'Branch-Router-01',name:'ether1',ip:'10.10.0.1/24',speed:'100 Mbps',status:'Down',vlan:'20',rx:'0 GB',tx:'0 GB'}
],
vlans:[
{id:21,id2:21,name:'Management',vlan:10,subnet:'10.0.0.0/24',gateway:'10.0.0.1',dhcp:'10.0.0.50-200',devices:12},
{id:22,id2:22,name:'Users',vlan:20,subnet:'10.0.20.0/24',gateway:'10.0.20.1',dhcp:'10.0.20.50-220',devices:84},
{id:23,id2:23,name:'Servers',vlan:30,subnet:'10.0.30.0/24',gateway:'10.0.30.1',dhcp:'Static',devices:26},
{id:24,id2:24,name:'Guest',vlan:40,subnet:'10.0.40.0/24',gateway:'10.0.40.1',dhcp:'10.0.40.50-240',devices:37}
],
alerts:[
{id:31,title:'Branch router unreachable',severity:'Critical',device:'Branch-Router-01',time:'2 minutes ago',status:'Open'},
{id:32,title:'Firewall CPU above 80%',severity:'Warning',device:'Edge-FW-01',time:'17 minutes ago',status:'Open'},
{id:33,title:'Interface utilization high',severity:'Warning',device:'Core-Switch-01',time:'1 hour ago',status:'Acknowledged'}
],
logs:[
{id:41,event:'Configuration backup completed',source:'Scheduler',time:'08:00'},
{id:42,event:'Core-Switch-01 interface Gi1/0/1 changed',source:'SNMP',time:'07:48'},
{id:43,event:'User admin logged in',source:'Auth',time:'07:42'}
],
settings:{name:'NetSphere Network',poll:60,theme:'light'}
};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
let state={page:'dashboard',search:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const toast=m=>{let x=document.querySelector('.toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2000)};
const badge=x=>{let c={Online:'green',Up:'green',Warning:'yellow',Offline:'red',Down:'red',Critical:'red',Acknowledged:'yellow',Open:'red',Closed:'green'}[x]||'gray';return `<span class="badge ${c}">${esc(x)}</span>`};
function shell(){document.querySelector('#app').innerHTML=`
<aside class="sidebar"><div class="brand">Net<b>Sphere</b></div><nav class="nav">
${[['dashboard','▦ Dashboard'],['devices','▣ Devices'],['interfaces','⇄ Interfaces'],['vlans','◈ VLANs & Subnets'],['topology','⌘ Topology'],['alerts','⚠ Alerts'],['logs','◷ Network Logs'],['monitoring','◉ Monitoring'],['reports','▥ Reports'],['settings','⚙ Settings']].map(([p,l])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${l}</button>`).join('')}
</nav></aside>
<main class="main"><header class="topbar"><div class="actions"><button class="btn mobile" onclick="document.querySelector('.sidebar').style.display='block'">☰</button><input class="search" placeholder="Search network..." value="${esc(state.search)}" oninput="state.search=this.value;render()"></div><div class="actions"><button class="btn" onclick="exportData()">Export</button><button class="btn primary" onclick="quickAdd()">+ Add</button></div></header><section class="container" id="page"></section></main>
<div class="modalbg" id="modal"><div class="modal" id="modalBody"></div></div><div class="toast"></div>`;renderPage()}
function go(p){state.page=p;state.search='';shell()} function render(){renderPage()}
function renderPage(){let f={dashboard,devices,interfaces,vlans,topology,alerts,logs,monitoring,reports,settings}[state.page];document.querySelector('#page').innerHTML=f()}
function stat(a,b,c){return `<div class="card"><div class="label">${a}</div><div class="value">${b}</div><div class="trend">${c}</div></div>`}
function dashboard(){let online=db.devices.filter(x=>x.status==='Online').length;let up=db.interfaces.filter(x=>x.status==='Up').length;return `<div class="head"><div><h1>Network Dashboard</h1><p>Infrastructure health and performance overview</p></div><button class="btn primary" onclick="openDevice()">+ Add Device</button></div>
<div class="grid stats">${stat('Total Devices',db.devices.length,online+' online')}${stat('Interfaces',db.interfaces.length,up+' links up')}${stat('Active VLANs',db.vlans.length,'All subnets healthy')}${stat('Open Alerts',db.alerts.filter(a=>a.status==='Open').length,'Requires attention')}</div><br>
<div class="grid two"><div class="card"><h3>Traffic — Last 12 Hours</h3><div class="chart">${[35,42,51,45,62,78,67,83,91,74,101,94].map((v,i)=>`<div style="flex:1;height:100%;display:flex;align-items:end"><div class="bar" style="height:${v*1.7}px;width:100%"><small>${i+1}h</small></div></div>`).join('')}</div></div>
<div class="card"><h3>Network Health</h3><div class="kv"><span>Devices online</span><strong>${online}/${db.devices.length}</strong></div><div class="kv"><span>Interfaces up</span><strong>${up}/${db.interfaces.length}</strong></div><div class="kv"><span>Open alerts</span><strong>${db.alerts.filter(a=>a.status==='Open').length}</strong></div><div class="kv"><span>Polling interval</span><strong>${db.settings.poll}s</strong></div></div></div><br>
<div class="grid two"><div class="card"><h3>Recent Alerts</h3>${db.alerts.slice(0,4).map(a=>`<div class="kv"><span>${esc(a.title)}<br><small>${esc(a.device)}</small></span>${badge(a.severity)}</div>`).join('')}</div><div class="card"><h3>Recent Events</h3><div class="activity">${db.logs.slice(0,4).map(l=>`<div class="act"><span class="dot"></span><div>${esc(l.event)}<br><small>${esc(l.source)} • ${esc(l.time)}</small></div></div>`).join('')}</div></div></div>`}
function devices(){let rows=db.devices.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase()));return `<div class="head"><div><h1>Network Devices</h1><p>Routers, switches, firewalls and infrastructure assets</p></div><button class="btn primary" onclick="openDevice()">+ New Device</button></div><div class="card"><div class="toolbar"><input placeholder="Filter devices..." value="${esc(state.search)}" oninput="state.search=this.value;render()"><select onchange="deviceFilter(this.value)"><option value="">All types</option><option>Router</option><option>Switch</option><option>Firewall</option><option>Access Point</option><option>Server</option></select><button class="btn" onclick="scan()">Run Discovery</button><button class="btn" onclick="resetData()">Reset Demo</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Device</th><th>Type</th><th>IP</th><th>MAC</th><th>Status</th><th>Site</th><th>Vendor</th><th>OS</th><th>Actions</th></tr></thead><tbody>${rows.map(d=>`<tr><td><strong>${esc(d.name)}</strong></td><td>${esc(d.type)}</td><td>${esc(d.ip)}</td><td>${esc(d.mac)}</td><td>${badge(d.status)}</td><td>${esc(d.site)}</td><td>${esc(d.vendor)}</td><td>${esc(d.os)}</td><td><button class="btn" onclick="openDevice(${d.id})">Edit</button> <button class="btn danger" onclick="remove('devices',${d.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No devices found</td></tr>'}</tbody></table></div></div>`}
function interfaces(){return `<div class="head"><div><h1>Interfaces</h1><p>Ports, IP addresses, VLANs and traffic counters</p></div><button class="btn primary" onclick="openInterface()">+ New Interface</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Device</th><th>Interface</th><th>IP</th><th>Speed</th><th>Status</th><th>VLAN</th><th>RX</th><th>TX</th><th>Actions</th></tr></thead><tbody>${db.interfaces.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase())).map(i=>`<tr><td>${esc(i.device)}</td><td>${esc(i.name)}</td><td>${esc(i.ip)}</td><td>${esc(i.speed)}</td><td>${badge(i.status)}</td><td>${esc(i.vlan)}</td><td>${esc(i.rx)}</td><td>${esc(i.tx)}</td><td><button class="btn" onclick="openInterface(${i.id})">Edit</button> <button class="btn danger" onclick="remove('interfaces',${i.id})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function vlans(){return `<div class="head"><div><h1>VLANs & Subnets</h1><p>Segmentation, gateways and address pools</p></div><button class="btn primary" onclick="openVlan()">+ New VLAN</button></div><div class="grid two">${db.vlans.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase())).map(v=>`<div class="card"><div class="kv"><strong>${esc(v.name)}</strong>${badge('VLAN '+v.vlan)}</div><div class="kv"><span>Subnet</span><strong>${esc(v.subnet)}</strong></div><div class="kv"><span>Gateway</span><strong>${esc(v.gateway)}</strong></div><div class="kv"><span>DHCP</span><strong>${esc(v.dhcp)}</strong></div><div class="kv"><span>Devices</span><strong>${v.devices}</strong></div><div style="margin-top:12px"><button class="btn" onclick="openVlan(${v.id})">Edit</button> <button class="btn danger" onclick="remove('vlans',${v.id})">Delete</button></div></div>`).join('')}</div>`}
function topology(){return `<div class="head"><div><h1>Network Topology</h1><p>Logical overview of core infrastructure</p></div><button class="btn" onclick="toast('Topology refreshed')">Refresh</button></div><div class="card topology">
<div class="link" style="left:30%;top:49%;width:40%;transform:rotate(0deg)"></div><div class="link" style="left:50%;top:30%;width:22%;transform:rotate(90deg)"></div><div class="link" style="left:50%;top:51%;width:24%;transform:rotate(25deg)"></div><div class="link" style="left:50%;top:51%;width:24%;transform:rotate(155deg)"></div>
<div class="node" style="left:45%;top:10%">Internet</div><div class="node" style="left:45%;top:42%">Edge-FW-01</div><div class="node" style="left:15%;top:42%">Core-Router-01</div><div class="node" style="left:68%;top:42%">Core-Switch-01</div><div class="node" style="left:12%;top:72%">Branch A</div><div class="node" style="left:69%;top:72%">Servers</div></div>`}
function alerts(){return `<div class="head"><div><h1>Alerts</h1><p>Events requiring network operations attention</p></div><button class="btn" onclick="ackAll()">Acknowledge All</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Alert</th><th>Severity</th><th>Device</th><th>Time</th><th>Status</th><th>Actions</th></tr></thead><tbody>${db.alerts.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase())).map(a=>`<tr><td><strong>${esc(a.title)}</strong></td><td>${badge(a.severity)}</td><td>${esc(a.device)}</td><td>${esc(a.time)}</td><td>${badge(a.status)}</td><td><button class="btn success" onclick="ack(${a.id})">Acknowledge</button> <button class="btn danger" onclick="remove('alerts',${a.id})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function logs(){return `<div class="head"><div><h1>Network Logs</h1><p>Operational and system event history</p></div><button class="btn" onclick="clearLogs()">Clear Logs</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Event</th><th>Source</th><th>Time</th><th>Action</th></tr></thead><tbody>${db.logs.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase())).map(l=>`<tr><td>${esc(l.event)}</td><td>${esc(l.source)}</td><td>${esc(l.time)}</td><td><button class="btn danger" onclick="remove('logs',${l.id})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function monitoring(){return `<div class="head"><div><h1>Live Monitoring</h1><p>Simulated SNMP-style infrastructure metrics</p></div><button class="btn primary" onclick="simulatePoll()">Poll Now</button></div><div class="grid three">${db.devices.map((d,i)=>`<div class="card"><div class="kv"><strong>${esc(d.name)}</strong>${badge(d.status)}</div><p>CPU</p><div class="progress"><i style="width:${35+i*13}%"></i></div><p>Memory</p><div class="progress"><i style="width:${42+i*9}%"></i></div><p>Traffic</p><div class="progress"><i style="width:${28+i*15}%"></i></div><small style="color:var(--muted)">Uptime: ${esc(d.uptime)}</small></div>`).join('')}</div>`}
function reports(){let online=db.devices.filter(x=>x.status==='Online').length;return `<div class="head"><div><h1>Network Reports</h1><p>Availability, inventory and capacity summaries</p></div><button class="btn" onclick="exportData()">Export JSON</button></div><div class="grid stats">${stat('Availability',db.devices.length?Math.round(online/db.devices.length*100)+'%':'0%','Device availability')}${stat('Total Interfaces',db.interfaces.length,'Inventory count')}${stat('VLAN Segments',db.vlans.length,'Configured segments')}${stat('Critical Alerts',db.alerts.filter(a=>a.severity==='Critical'&&a.status==='Open').length,'Open critical')}</div><br><div class="grid two"><div class="card"><h3>Device Types</h3>${['Router','Switch','Firewall','Access Point','Server'].map(t=>{let n=db.devices.filter(d=>d.type===t).length;return `<div class="kv"><span>${t}</span><strong>${n}</strong></div>`}).join('')}</div><div class="card"><h3>VLAN Utilization</h3>${db.vlans.map(v=>`<p>${esc(v.name)} <span style="float:right">${v.devices} devices</span></p><div class="progress"><i style="width:${Math.min(100,v.devices)}%"></i></div>`).join('')}</div></div>`}
function settings(){return `<div class="head"><div><h1>Settings</h1><p>Configure your network management workspace</p></div><button class="btn primary" onclick="saveSettings()">Save Changes</button></div><div class="card"><div class="form"><div class="field"><label>Workspace Name</label><input id="sName" value="${esc(db.settings.name)}"></div><div class="field"><label>Polling Interval (seconds)</label><input id="sPoll" type="number" value="${db.settings.poll}"></div><div class="field"><label>Theme</label><select id="sTheme"><option>light</option><option>dark</option></select></div><div class="field"><label>Backup</label><button class="btn" onclick="exportData()">Export Configuration</button></div></div></div>`}
function modal(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').classList.add('show')}function closeModal(){document.querySelector('#modal').classList.remove('show')}function field(id,l,v,t='text'){return `<div class="field"><label>${l}</label><input id="${id}" type="${t}" value="${esc(v)}"></div>`}function select(id,l,opts,v){return `<div class="field"><label>${l}</label><select id="${id}">${opts.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select></div>`}function val(id){return document.getElementById(id).value}
function openDevice(id=null){let d=id?db.devices.find(x=>x.id===id):{name:'',type:'Router',ip:'',mac:'',status:'Online',site:'HQ',vendor:'Cisco',model:'',os:'',uptime:'0d'};modal(`<h2>${id?'Edit':'New'} Device</h2><div class="form">${field('dn','Device Name',d.name)}${select('dt','Type',['Router','Switch','Firewall','Access Point','Server'],d.type)}${field('dip','IP Address',d.ip)}${field('dmac','MAC Address',d.mac)}${select('ds','Status',['Online','Warning','Offline'],d.status)}${field('dsite','Site',d.site)}${field('dv','Vendor',d.vendor)}${field('dm','Model',d.model)}${field('dos','OS',d.os)}</div><div class="foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveDevice(${id||0})">Save</button></div>`)}
function saveDevice(id){let o={name:val('dn'),type:val('dt'),ip:val('dip'),mac:val('dmac'),status:val('ds'),site:val('dsite'),vendor:val('dv'),model:val('dm'),os:val('dos'),uptime:'0d'};if(id)Object.assign(db.devices.find(x=>x.id===id),o);else db.devices.push({id:Date.now(),...o});save();db.logs.unshift({id:Date.now(),event:`${id?'Updated':'Added'} device ${o.name}`,source:'Admin',time:'Just now'});closeModal();renderPage();toast('Device saved')}
function openInterface(id=null){let i=id?db.interfaces.find(x=>x.id===id):{device:db.devices[0]?.name||'',name:'',ip:'',speed:'1 Gbps',status:'Up',vlan:'10',rx:'0 GB',tx:'0 GB'};modal(`<h2>${id?'Edit':'New'} Interface</h2><div class="form">${field('idv','Device',i.device)}${field('in','Interface',i.name)}${field('iip','IP/CIDR',i.ip)}${field('isp','Speed',i.speed)}${select('ist','Status',['Up','Down'],i.status)}${field('iv','VLAN',i.vlan)}${field('ir','RX',i.rx)}${field('it','TX',i.tx)}</div><div class="foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveInterface(${id||0})">Save</button></div>`)}
function saveInterface(id){let o={device:val('idv'),name:val('in'),ip:val('iip'),speed:val('isp'),status:val('ist'),vlan:val('iv'),rx:val('ir'),tx:val('it')};if(id)Object.assign(db.interfaces.find(x=>x.id===id),o);else db.interfaces.push({id:Date.now(),...o});save();closeModal();renderPage();toast('Interface saved')}
function openVlan(id=null){let v=id?db.vlans.find(x=>x.id===id):{name:'',vlan:50,subnet:'',gateway:'',dhcp:'',devices:0};modal(`<h2>${id?'Edit':'New'} VLAN</h2><div class="form">${field('vn','Name',v.name)}${field('vv','VLAN ID',v.vlan,'number')}${field('vs','Subnet',v.subnet)}${field('vg','Gateway',v.gateway)}${field('vd','DHCP Pool',v.dhcp)}${field('vc','Device Count',v.devices,'number')}</div><div class="foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveVlan(${id||0})">Save</button></div>`)}
function saveVlan(id){let o={name:val('vn'),vlan:+val('vv'),subnet:val('vs'),gateway:val('vg'),dhcp:val('vd'),devices:+val('vc')||0};if(id)Object.assign(db.vlans.find(x=>x.id===id),o);else db.vlans.push({id:Date.now(),...o});save();closeModal();renderPage();toast('VLAN saved')}
function remove(type,id){if(confirm('Delete this item?')){db[type]=db[type].filter(x=>x.id!==id);save();renderPage();toast('Deleted')}}function ack(id){let a=db.alerts.find(x=>x.id===id);a.status='Acknowledged';save();renderPage();toast('Alert acknowledged')}function ackAll(){db.alerts.forEach(a=>a.status='Acknowledged');save();renderPage();toast('All alerts acknowledged')}
function scan(){db.logs.unshift({id:Date.now(),event:'Network discovery scan completed',source:'Discovery',time:'Just now'});save();toast('Discovery completed');renderPage()}function simulatePoll(){db.logs.unshift({id:Date.now(),event:'Manual monitoring poll completed',source:'Monitor',time:'Just now'});save();toast('Poll completed');renderPage()}function clearLogs(){if(confirm('Clear all logs?')){db.logs=[];save();renderPage()}}function deviceFilter(x){state.search=x;render()}function quickAdd(){if(state.page==='devices')openDevice();else if(state.page==='interfaces')openInterface();else if(state.page==='vlans')openVlan();else openDevice()}
function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='netsphere-network-config.json';a.click();URL.revokeObjectURL(a.href);toast('Configuration exported')}
function resetData(){if(confirm('Reset demo network data?')){localStorage.removeItem(KEY);db=JSON.parse(JSON.stringify(seed));renderPage();toast('Demo reset')}}function saveSettings(){db.settings.name=val('sName');db.settings.poll=+val('sPoll')||60;db.settings.theme=val('sTheme');save();toast('Settings saved')}
document.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});shell();
// alert ack flow
